// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: importer.proto

package importer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRecordType int32

const (
	ScanRecordType_SCAN_RECORD_TYPE_UNSPECIFIED ScanRecordType = 0
	ScanRecordType_SCAN_RECORD_TYPE_FILE        ScanRecordType = 1
	ScanRecordType_SCAN_RECORD_TYPE_DIRECTORY   ScanRecordType = 2
	ScanRecordType_SCAN_RECORD_TYPE_SYMLINK     ScanRecordType = 3
	ScanRecordType_SCAN_RECORD_TYPE_DEVICE      ScanRecordType = 4
	ScanRecordType_SCAN_RECORD_TYPE_PIPE        ScanRecordType = 5
	ScanRecordType_SCAN_RECORD_TYPE_SOCKET      ScanRecordType = 6
)

// Enum value maps for ScanRecordType.
var (
	ScanRecordType_name = map[int32]string{
		0: "SCAN_RECORD_TYPE_UNSPECIFIED",
		1: "SCAN_RECORD_TYPE_FILE",
		2: "SCAN_RECORD_TYPE_DIRECTORY",
		3: "SCAN_RECORD_TYPE_SYMLINK",
		4: "SCAN_RECORD_TYPE_DEVICE",
		5: "SCAN_RECORD_TYPE_PIPE",
		6: "SCAN_RECORD_TYPE_SOCKET",
	}
	ScanRecordType_value = map[string]int32{
		"SCAN_RECORD_TYPE_UNSPECIFIED": 0,
		"SCAN_RECORD_TYPE_FILE":        1,
		"SCAN_RECORD_TYPE_DIRECTORY":   2,
		"SCAN_RECORD_TYPE_SYMLINK":     3,
		"SCAN_RECORD_TYPE_DEVICE":      4,
		"SCAN_RECORD_TYPE_PIPE":        5,
		"SCAN_RECORD_TYPE_SOCKET":      6,
	}
)

func (x ScanRecordType) Enum() *ScanRecordType {
	p := new(ScanRecordType)
	*p = x
	return p
}

func (x ScanRecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanRecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_importer_proto_enumTypes[0].Descriptor()
}

func (ScanRecordType) Type() protoreflect.EnumType {
	return &file_importer_proto_enumTypes[0]
}

func (x ScanRecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanRecordType.Descriptor instead.
func (ScanRecordType) EnumDescriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{0}
}

type InfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Origin string `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Root   string `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InfoResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *InfoResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type ScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{2}
}

type ScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pathname string `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	// Types that are assignable to Result:
	//
	//	*ScanResponse_Error
	//	*ScanResponse_Record
	Result isScanResponse_Result `protobuf_oneof:"result"`
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{3}
}

func (x *ScanResponse) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (m *ScanResponse) GetResult() isScanResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ScanResponse) GetError() *ScanError {
	if x, ok := x.GetResult().(*ScanResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (x *ScanResponse) GetRecord() *ScanRecord {
	if x, ok := x.GetResult().(*ScanResponse_Record); ok {
		return x.Record
	}
	return nil
}

type isScanResponse_Result interface {
	isScanResponse_Result()
}

type ScanResponse_Error struct {
	Error *ScanError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ScanResponse_Record struct {
	Record *ScanRecord `protobuf:"bytes,2,opt,name=record,proto3,oneof"`
}

func (*ScanResponse_Error) isScanResponse_Result() {}

func (*ScanResponse_Record) isScanResponse_Result() {}

type ScanError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ScanError) Reset() {
	*x = ScanError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanError) ProtoMessage() {}

func (x *ScanError) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanError.ProtoReflect.Descriptor instead.
func (*ScanError) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{4}
}

func (x *ScanError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ScanRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type               ScanRecordType        `protobuf:"varint,1,opt,name=type,proto3,enum=importer.ScanRecordType" json:"type,omitempty"`
	Target             string                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Fileinfo           *ScanRecordFileInfo   `protobuf:"bytes,3,opt,name=fileinfo,proto3" json:"fileinfo,omitempty"`
	Children           []*ScanRecordFileInfo `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	ExtendedAttributes map[string][]byte     `protobuf:"bytes,5,rep,name=extended_attributes,json=extendedAttributes,proto3" json:"extended_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FileAttributes     []string              `protobuf:"bytes,6,rep,name=file_attributes,json=fileAttributes,proto3" json:"file_attributes,omitempty"`
}

func (x *ScanRecord) Reset() {
	*x = ScanRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRecord) ProtoMessage() {}

func (x *ScanRecord) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRecord.ProtoReflect.Descriptor instead.
func (*ScanRecord) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{5}
}

func (x *ScanRecord) GetType() ScanRecordType {
	if x != nil {
		return x.Type
	}
	return ScanRecordType_SCAN_RECORD_TYPE_UNSPECIFIED
}

func (x *ScanRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ScanRecord) GetFileinfo() *ScanRecordFileInfo {
	if x != nil {
		return x.Fileinfo
	}
	return nil
}

func (x *ScanRecord) GetChildren() []*ScanRecordFileInfo {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ScanRecord) GetExtendedAttributes() map[string][]byte {
	if x != nil {
		return x.ExtendedAttributes
	}
	return nil
}

func (x *ScanRecord) GetFileAttributes() []string {
	if x != nil {
		return x.FileAttributes
	}
	return nil
}

type ScanRecordFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size      int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode      int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Dev       uint64                 `protobuf:"varint,5,opt,name=dev,proto3" json:"dev,omitempty"`
	Ino       uint64                 `protobuf:"varint,6,opt,name=ino,proto3" json:"ino,omitempty"`
	Uid       uint64                 `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid       uint64                 `protobuf:"varint,8,opt,name=gid,proto3" json:"gid,omitempty"`
	Nlink     uint32                 `protobuf:"varint,9,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Username  string                 `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	Groupname string                 `protobuf:"bytes,11,opt,name=groupname,proto3" json:"groupname,omitempty"`
}

func (x *ScanRecordFileInfo) Reset() {
	*x = ScanRecordFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanRecordFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRecordFileInfo) ProtoMessage() {}

func (x *ScanRecordFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRecordFileInfo.ProtoReflect.Descriptor instead.
func (*ScanRecordFileInfo) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{6}
}

func (x *ScanRecordFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScanRecordFileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ScanRecordFileInfo) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ScanRecordFileInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *ScanRecordFileInfo) GetDev() uint64 {
	if x != nil {
		return x.Dev
	}
	return 0
}

func (x *ScanRecordFileInfo) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *ScanRecordFileInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ScanRecordFileInfo) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ScanRecordFileInfo) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *ScanRecordFileInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ScanRecordFileInfo) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

type ScanResponseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ScanResponseError) Reset() {
	*x = ScanResponseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponseError) ProtoMessage() {}

func (x *ScanResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponseError.ProtoReflect.Descriptor instead.
func (*ScanResponseError) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{7}
}

func (x *ScanResponseError) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScanResponseError) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pathname string `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{8}
}

func (x *ReadRequest) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_importer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{9}
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_importer_proto protoreflect.FileDescriptor

var file_importer_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x0c, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x0c, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x74, 0x68, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x74, 0x68, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x2e, 0x53, 0x63, 0x61, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53,
	0x63, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x25, 0x0a,
	0x09, 0x53, 0x63, 0x61, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x95, 0x03, 0x0a, 0x0a, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x61,
	0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x38, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x69,
	0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x12, 0x5d, 0x0a,
	0x13, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x12, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x45, 0x0a, 0x17, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65,
	0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x9f, 0x02, 0x0a,
	0x12, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12,
	0x35, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x6d,
	0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x76, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x64, 0x65, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x6e, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x67, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e,
	0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b,
	0x0a, 0x11, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x29, 0x0a, 0x0b, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x74, 0x68, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x74, 0x68, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0xe0, 0x01, 0x0a, 0x0e, 0x53,
	0x63, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a,
	0x1c, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x19, 0x0a, 0x15, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x43,
	0x41, 0x4e, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44,
	0x49, 0x52, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x43,
	0x41, 0x4e, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x59, 0x4d, 0x4c, 0x49, 0x4e, 0x4b, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x43, 0x41, 0x4e,
	0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x56,
	0x49, 0x43, 0x45, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x52, 0x45,
	0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x49, 0x50, 0x45, 0x10, 0x05,
	0x12, 0x1b, 0x0a, 0x17, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x4f, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x06, 0x32, 0xb3, 0x01,
	0x0a, 0x08, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x15, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x15, 0x2e, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x37, 0x0a, 0x04, 0x52, 0x65,
	0x61, 0x64, 0x12, 0x15, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_importer_proto_rawDescOnce sync.Once
	file_importer_proto_rawDescData = file_importer_proto_rawDesc
)

func file_importer_proto_rawDescGZIP() []byte {
	file_importer_proto_rawDescOnce.Do(func() {
		file_importer_proto_rawDescData = protoimpl.X.CompressGZIP(file_importer_proto_rawDescData)
	})
	return file_importer_proto_rawDescData
}

var file_importer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_importer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_importer_proto_goTypes = []any{
	(ScanRecordType)(0),           // 0: importer.ScanRecordType
	(*InfoRequest)(nil),           // 1: importer.InfoRequest
	(*InfoResponse)(nil),          // 2: importer.InfoResponse
	(*ScanRequest)(nil),           // 3: importer.ScanRequest
	(*ScanResponse)(nil),          // 4: importer.ScanResponse
	(*ScanError)(nil),             // 5: importer.ScanError
	(*ScanRecord)(nil),            // 6: importer.ScanRecord
	(*ScanRecordFileInfo)(nil),    // 7: importer.ScanRecordFileInfo
	(*ScanResponseError)(nil),     // 8: importer.ScanResponseError
	(*ReadRequest)(nil),           // 9: importer.ReadRequest
	(*ReadResponse)(nil),          // 10: importer.ReadResponse
	nil,                           // 11: importer.ScanRecord.ExtendedAttributesEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_importer_proto_depIdxs = []int32{
	5,  // 0: importer.ScanResponse.error:type_name -> importer.ScanError
	6,  // 1: importer.ScanResponse.record:type_name -> importer.ScanRecord
	0,  // 2: importer.ScanRecord.type:type_name -> importer.ScanRecordType
	7,  // 3: importer.ScanRecord.fileinfo:type_name -> importer.ScanRecordFileInfo
	7,  // 4: importer.ScanRecord.children:type_name -> importer.ScanRecordFileInfo
	11, // 5: importer.ScanRecord.extended_attributes:type_name -> importer.ScanRecord.ExtendedAttributesEntry
	12, // 6: importer.ScanRecordFileInfo.mod_time:type_name -> google.protobuf.Timestamp
	1,  // 7: importer.Importer.Info:input_type -> importer.InfoRequest
	3,  // 8: importer.Importer.Scan:input_type -> importer.ScanRequest
	9,  // 9: importer.Importer.Read:input_type -> importer.ReadRequest
	2,  // 10: importer.Importer.Info:output_type -> importer.InfoResponse
	4,  // 11: importer.Importer.Scan:output_type -> importer.ScanResponse
	10, // 12: importer.Importer.Read:output_type -> importer.ReadResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_importer_proto_init() }
func file_importer_proto_init() {
	if File_importer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_importer_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*InfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_importer_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*InfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_importer_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_importer_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_importer_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ScanError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_importer_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ScanRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_importer_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ScanRecordFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_importer_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ScanResponseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_importer_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_importer_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_importer_proto_msgTypes[3].OneofWrappers = []any{
		(*ScanResponse_Error)(nil),
		(*ScanResponse_Record)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_importer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_importer_proto_goTypes,
		DependencyIndexes: file_importer_proto_depIdxs,
		EnumInfos:         file_importer_proto_enumTypes,
		MessageInfos:      file_importer_proto_msgTypes,
	}.Build()
	File_importer_proto = out.File
	file_importer_proto_rawDesc = nil
	file_importer_proto_goTypes = nil
	file_importer_proto_depIdxs = nil
}
